// angular/crud/src/app/components/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api.service';
import { Employee } from '../models/employee.model';

declare var $: any;

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

    /**
     * Records from server
     */
    arrRecords: Array<Employee> = [];

    /**
     * Record to edit
     */
    recordToEdit: Employee;


    constructor(
        private apiService: ApiService
    ) {}


    /**
     * Init here
     */
    ngOnInit(): void {
        this.getAllRecords();
    }


    /**
     * ADD / UPDATE RECORD
     */
    saveChanges() {

        /**
         * Get input from user. 
         * We use jquery for simplicity only
         */
        const name = $('#name').val();
        const age = $('#age').val();
        const position = $('#position').val();

        /**
         * Validate not empty
         */
        if (!name || !age || !position) {
            $('#addNewInfo').html('Please fill all fields');
            return;
        }

        /**
         * This is our data to save
         */
        const data = {
            name,
            age,
            position
        };

        if (this.recordToEdit) {

            /**
             * Update values
             */
            this.apiService.updateChanges(this.recordToEdit._id, data).subscribe( () => {
                this.getAllRecords();
                this.cancelAdd();
            });

        } else {

            /**
             * Insert new record
             */
            this.apiService.addRecord(data).subscribe( () => {
                this.getAllRecords();
                this.cancelAdd();
            });

        }

    }

    /**
     * GET ALL RECORDS FROM SERVER
     */
    getAllRecords() {
        this.apiService.getAllRecords().subscribe( (response: any) => {
            if (response.count) {
                this.arrRecords = response.data;
            }
        });
    }


    /**
     * DELETE RECORD
     */
    deleteRecord(id: string) {
        if (confirm('Are you sure?') === false) {
            return;
        }
        this.apiService.deleteRecord(id).subscribe( () => {
            this.getAllRecords();
        });
    }


    /**
     * FIND RECORD BY ID
     */
    getRecordById(id: string) {
        this.apiService.getRecordById(id).subscribe( (response: any) => {
            if (response.count) {
                this.recordToEdit = response.data[0];
                this.showAddNew();
            }
        });
    }


    /**
     * Simply shows a DIV
     */
    showAddNew() {
        $('#newRecordDiv').slideDown('fast');
    }

    /**
     * Simply hides a DIV
     */
    cancelAdd() {
        $('#id').val('');
        $('#name').val('');
        $('#age').val('');
        $('#position').val('');
        $('#recordId').hide();
        $('#newRecordDiv').slideUp('fast');
        this.recordToEdit = null;
    }

}


<div class="container mt-4">

    <!--
        Intro card
    -->
    <div class="card border-0 shadow">
        <div class="card-header">
            <h5>CRUD Demo App - Vaskit</h5>
        </div>
        <div class="card-body">

            <p class="card-text">
                Welcome! This demo app shows how you can use VASKIT to
                create, remove, update and delete records.
            </p>

            <div class="card-text mt-4">
                <h5>Things you will need:</h5>
            </div>

            <ul class="list-group mt-4">
                <li class="list-group-item">
                    1) A VASKIT account. Go <a href="https://vaskit.com">here</a> to get one.
                </li>
                <li class="list-group-item">
                    2) Your DEVELOPER KEY. You get this from your <a href="https://vaskit.com/dashboard">Dashboard</a>
                </li>
                <li class="list-group-item">
                    You can find this code in our <a href="">repository</a>
                </li>
                <li class="list-group-item">
                    This is a very simple example. Click <a href="/doc">here</a>
                    and learn about users and records security to make them private
                    or accessible to certain users only.
                    Learn how to send <b>PUSH</b> messages and use <b>SOCKET</b> communication.
                </li>
            </ul>

        </div>
    </div>


    <!--
        CRUD Card
    -->
    <div class="card border-0 shadow mt-4 mb-4">
        <div class="card-header">
            <h5>List of Employees</h5>
        </div>
        <div class="card-body">

            <p class="card-text">
                For this demo we will run CRUD operations for a group of employees.
            </p>

            <table class="table border">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Position</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="employeesList">
                    <tr *ngFor="let item of arrRecords">
                        <td>{{ item.data.name }}</td>
                        <td>{{ item.data.age }}</td>
                        <td>{{ item.data.position }}</td>
                        <td>
                            <button class="btn btn-danger mr-2" (click)="deleteRecord(item._id)">
                                Delete
                            </button>
                            <button class="btn btn-primary" (click)="getRecordById(item._id)">
                                Edit
                            </button>                        
                        </td>
                    </tr>
                </tbody>
            </table>


            <!--
                Add new record
            -->
            <div class="mt-4 mb-4" align="center" id="newRecordDiv" style="display:none">
                <table class="table table-borderless" style="max-width:400px">
                    
                    <tr id="recordId" *ngIf="recordToEdit">
                        <td>Record ID:</td>
                        <td><input type="text" id="id" disabled class="form-control" 
                            [value]="recordToEdit._id" /></td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td><input type="text" id="name" class="form-control" 
                            [value]="recordToEdit ? recordToEdit.data.name : ''" /></td>
                    </tr>
                    <tr>
                        <td>Age:</td>
                        <td><input type="number" id="age" class="form-control" 
                            [value]="recordToEdit ? recordToEdit.data.age : ''" /></td>
                    </tr>
                    <tr>
                        <td>Position:</td>
                        <td><input type="text" id="position" class="form-control" 
                            [value]="recordToEdit ? recordToEdit.data.position : ''" /></td>
                    </tr>
                </table>
                <table class="table table-borderless" style="max-width:400px">
                    <tr>
                        <td>
                            <div id="addNewInfo" class="text-info">
                            </div>
                        </td>
                        <td align="right" width="230">
                            <button class="btn btn-secondary mr-2" (click)="cancelAdd()">
                                Cancel
                            </button>
                            <button class="btn btn-primary" (click)="saveChanges()">
                                Save
                            </button>
                        </td>
                    </tr>
                </table>
            </div>

        </div>
        <div class="card-footer text-center">
            <button class="btn btn-primary" (click)="showAddNew()">
                Add New
            </button>
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-body text-center">
            Clone this code from <a href="">Github</a>
        </div>
    </div>

    <div style="height:5rem"></div>

</div>

// react/crud/src/App.js
import React, { Component } from 'react';
import './App.css';
import Employees from './components/Employees';
import AddEmployee from './components/AddEmployee';
import EditEmployee from './components/EditEmployee';
import axios from 'axios';

class App extends Component {

    /**
     * Main configuration here
     */
    state = {
        /**
         * VASKIT API endpoint
         */
        ENDPOINT: 'https://vaskit.com',
        /**
         * Replace here with your developer key
         */
        DEVELOPER_KEY: 'REPLACE WITH A VALID DEVELOPER KEY HERE',

        employees: [],

        employeeSelected: null
    }

    /**
     * Start here
     */
    componentDidMount() {
        this.getAllRecords();
    }

    /**
     * GET ALL RECRODS FROM VASKIT
     */
    getAllRecords = () => {
        axios({
            method: 'post',
            url: this.state.ENDPOINT + '/record/api/find',
            data: {
                table: 'employees'
            },
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'jwt ',
                'key': this.state.DEVELOPER_KEY
            }
        }).then( response => {
            this.setState({
                employees: response.data.data
            })
        })
    }


    /**
     * SAVE NEW RECORD AT VASKIT
     */
    saveNew = (employee) => {
        axios({
            method: 'post',
            url: this.state.ENDPOINT + '/record/api',
            data: {
                /**
                 * Table name where this record will be inserterd.
                 * You must create these tables from your Dashboard
                 * https://vaskit.com/dashboard
                 */
                table: 'employees',

                /**
                 * This is the data to insert in your table
                 */
                data: {
                    name: employee.name, 
                    age: employee.age,
                    position: employee.position
                },

                /**
                 * You can define this record security
                 */
                readPublic: true,
                writePublic: true,
                readUsers: [/** Your user's IDs who can read this record separated by comma */],
                writeUsers: [/** Your user's IDs who can write this record separated by comma */]

            },
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'jwt ',
                'key': this.state.DEVELOPER_KEY
            }
        }).then( () => {
            this.getAllRecords();
        })
    }


    /**
     * DELETE RECORD FROM VASKIT
     */
    deleteRecord = (id) => {
        if (window.confirm('Are you sure?') === false) return;
        axios({
            method: 'delete',
            url: this.state.ENDPOINT + '/record/api/' + id,
            data: {
                table: 'employees'
            },
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'jwt ',
                'key': this.state.DEVELOPER_KEY
            }
        }).then( response => {
            this.getAllRecords();
        })
    }

    selectEmployee = (id) => {
        this.setState({
            employeeSelected: this.state.employees.find( item => {
                return item._id == id
            })
        })
    }

    updateExistent = (data) => {
        axios({
            method: 'put',
            url: this.state.ENDPOINT + '/record/api/' + data._id,
            data: {
                table: 'employees',
                data
            },
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'jwt ',
                'key': this.state.DEVELOPER_KEY
            }
        }).then( () => {
            this.getAllRecords();
            this.setState({
                employeeSelected: null
            })
        })
    }

    cancel = () => {
        this.setState({
            employeeSelected: null
        })
    }

    render() {
        return (
            <div className="container mt-4">

                <div className="card border-0 shadow">
                    <div className="card-header">
                        <h5>CRUD Demo App - Vaskit</h5>
                    </div>
                    <div className="card-body">
                        <p className="card-text">
                            Welcome! This demo app shows how you can use VASKIT to
                            create, remove, update and delete records.
                        </p>
                        <div className="card-text mt-4">
                            <h5>Things you will need:</h5>
                        </div>
                        <ul className="list-group mt-4">
                            <li className="list-group-item">
                                1) A VASKIT account. Go <a href="https://vaskit.com">here</a> 
                                to get one.
                            </li>
                            <li className="list-group-item">
                                2) Your DEVELOPER KEY. You get this from your 
                                <a href="https://vaskit.com/dashboard">Dashboard</a>
                            </li>
                            <li className="list-group-item">
                                3) From your 
                                <a href="https://vaskit.com/dashboard">Dashboard</a>, 
                                create a table called employees
                            </li>
                            <li className="list-group-item">
                                Click <a href="https://vaskit.com/doc">here</a>&nbsp;
                                and learn about users and records security to make them private
                                or accessible to certain users only.
                                Learn how to send <b>PUSH</b> messages and use <b>SOCKET</b> 
                                communication.
                            </li>
                        </ul>
                    </div>
                </div>

                <div className="card border-0 shadow mt-4 mb-4">
                    <div className="card-header">
                        <h5>List of Employees</h5>
                    </div>
                    <div className="card-body">
                        <p className="card-text">
                            For this demo we will run CRUD operations 
                            for a group of employees.
                        </p>
                        <table className="table border">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Age</th>
                                    <th>Position</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="employeesList">
                                <Employees 
                                    employees={this.state.employees}
                                    deleteRecord={this.deleteRecord} 
                                    selectEmployee={this.selectEmployee}
                                />
                            </tbody>
                        </table>
                    </div>
                </div>

                { this.state.employeeSelected ? (
                    <EditEmployee 
                        employeeSelected={this.state.employeeSelected}
                        updateExistent={this.updateExistent} 
                        cancel={this.cancel}
                    />
                ) : (
                    <AddEmployee 
                        saveNew={this.saveNew} 
                    />
                )}

            </div>
        );
    }
}

export default App;
